spring:
  datasource:
    druid:
      url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:orion_visor}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&rewriteBatchedStatements=true&useServerPrepStmts=false
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASSWORD:Data@123456}
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 20
      # 控制台
      stat-view-servlet:
        enabled: true
        login-username: ${DRUID_USERNAME:admin}
        login-password: ${DRUID_PASSWORD:admin}
      web-stat-filter:
        enabled: true
      filter:
        stat:
          enabled: true
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:Data@123456}
    database: ${REDIS_DATABASE:0}
    data-version: ${REDIS_DATA_VERSION:2}
  redisson:
    threads: 4
    netty-threads: 4
    minimum-idle-size: 4
  influxdb:
    enabled: ${INFLUXDB_ENABLED:true}
    url: http://${INFLUXDB_HOST:127.0.0.1}:${INFLUXDB_PORT:8086}
    org: ${INFLUXDB_ORG:orion-visor}
    bucket: ${INFLUXDB_BUCKET:metrics}
    token: ${INFLUXDB_TOKEN:Data@123456}
  quartz:
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 10
  boot:
    admin:
      client:
        enabled: true
      server:
        enabled: true

guacd:
  host: ${GUACD_HOST:127.0.0.1}
  port: ${GUACD_PORT:4822}
  drive-path: ${GUACD_DRIVE_PATH:/usr/share/guacd/drive}

management:
  endpoints:
    enabled-by-default: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

knife4j:
  enable: false
  production: true

orion:
  # 是否为演示模式
  demo: ${DEMO_MODE:false}
  api:
    # 是否允许跨域
    cors: ${API_CORS:true}
    expose:
      # 暴露接口请求头值
      token: ${API_EXPOSE_TOKEN:pmqeHOyZaumHm0Wt}
  logging:
    printer:
      mode: PRETTY
  encrypt:
    aes:
      # 加密密钥
      secret-key: ${SECRET_KEY:uQeacXV8b3isvKLK}

app:
  executors:
    # 默认异步线程池
    asyncExecutor:
      mdc: true
      core-pool-size: 8
      max-pool-size: 16
      queue-capacity: 100
      allow-core-timeout: false
      thread-name-prefix: async-executor-
    # 指标存储异步线程池
    metricsExecutor:
      mdc: true
      core-pool-size: 4
      max-pool-size: 4
      queue-capacity: 1000
      allow-core-timeout: true
      thread-name-prefix: metrics-task-
    # 推送异步线程池
    pushExecutor:
      mdc: true
      core-pool-size: 4
      max-pool-size: 4
      queue-capacity: 1000
      allow-core-timeout: true
      thread-name-prefix: message-push-
    # 探针安装线程池
    agentInstallExecutor:
      allow-core-timeout: true
      thread-name-prefix: agent-install-
    # 终端标准输出线程池
    terminalStdoutExecutor:
      synchronous-queue: true
      allow-core-timeout: true
      thread-name-prefix: terminal-stdout-
    # 终端操作线程池
    terminalOperatorExecutor:
      synchronous-queue: true
      allow-core-timeout: true
      thread-name-prefix: terminal-operator-
    # 终端异步保存线程池
    terminalAsyncSaverExecutor:
      core-pool-size: 1
      max-pool-size: 1
      queue-capacity: 1000
      allow-core-timeout: true
      thread-name-prefix: terminal-watcher-
    # 批量执行超时检查线程池
    execTimeoutCheckExecutor:
      synchronous-queue: true
      allow-core-timeout: true
      thread-name-prefix: timeout-check-
    # 批量执行任务线程池
    execTaskExecutor:
      synchronous-queue: true
      allow-core-timeout: true
      thread-name-prefix: exec-task-
    # 批量执行主机命令线程池
    execHostCommandExecutor:
      synchronous-queue: true
      allow-core-timeout: true
      thread-name-prefix: exec-host-
    # 批量执行日志查看线程池
    execLogViewExecutor:
      synchronous-queue: true
      allow-core-timeout: true
      thread-name-prefix: exec-log-
    # 批量上传任务线程池
    uploadTaskExecutor:
      synchronous-queue: true
      allow-core-timeout: true
      thread-name-prefix: upload-task-
    # 批量上传主机线程池
    uploadHostExecutor:
      synchronous-queue: true
      allow-core-timeout: true
      thread-name-prefix: upload-host-
