spring:
  datasource:
    druid:
      url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:orion_visor}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&rewriteBatchedStatements=true&useServerPrepStmts=false
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASSWORD:Data@123456}
      initial-size: 0
      min-idle: 1
      max-active: 5
      stat-view-servlet:
        enabled: false
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:Data@123456}
    database: ${REDIS_DATABASE:1}
    data-version: ${REDIS_DATA_VERSION:2}
    mock: false
  redisson:
    threads: 2
    netty-threads: 2
    minimum-idle-size: 2
  influxdb:
    enabled: ${INFLUXDB_ENABLED:true}
    url: http://${INFLUXDB_HOST:127.0.0.1}:${INFLUXDB_PORT:8086}
    org: ${INFLUXDB_ORG:orion-visor}
    bucket: ${INFLUXDB_BUCKET:metrics}
    token: ${INFLUXDB_TOKEN:Data@123456}
  boot:
    admin:
      client:
        enabled: false
      server:
        enabled: false

guacd:
  host: ${GUACD_HOST:127.0.0.1}
  port: ${GUACD_PORT:4822}
  drive-path: ${GUACD_DRIVE_PATH:/home/guacd/drive}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: shutdown

mybatis-plus:
  configuration:
    # 日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  executors:
    # 默认异步线程池
    asyncExecutor:
      mdc: true
      core-pool-size: 2
      max-pool-size: 4
      queue-capacity: 30
      allow-core-timeout: false
      thread-name-prefix: async-executor-
    # 指标存储异步线程池
    metricsExecutor:
      mdc: true
      core-pool-size: 2
      max-pool-size: 2
      queue-capacity: 1000
      allow-core-timeout: true
      thread-name-prefix: metrics-task-
    # 推送异步线程池
    pushExecutor:
      mdc: true
      core-pool-size: 1
      max-pool-size: 1
      queue-capacity: 1000
      allow-core-timeout: true
      thread-name-prefix: message-push-
    # 探针安装线程池
    agentInstallExecutor:
      core-pool-size: 2
      max-pool-size: 2
      queue-capacity: 200
      allow-core-timeout: true
      thread-name-prefix: agent-install-
    # 终端标准输出线程池
    terminalStdoutExecutor:
      synchronous-queue: true
      allow-core-timeout: true
      thread-name-prefix: terminal-stdout-
    # 终端操作线程池
    terminalOperatorExecutor:
      synchronous-queue: true
      allow-core-timeout: true
      thread-name-prefix: terminal-operator-
    # 终端异步保存线程池
    terminalAsyncSaverExecutor:
      core-pool-size: 1
      max-pool-size: 1
      queue-capacity: 1000
      allow-core-timeout: true
      thread-name-prefix: terminal-watcher-
    # 批量执行超时检查线程池
    execTimeoutCheckExecutor:
      synchronous-queue: true
      allow-core-timeout: true
      thread-name-prefix: timeout-check-
    # 批量执行任务线程池
    execTaskExecutor:
      synchronous-queue: true
      allow-core-timeout: true
      thread-name-prefix: exec-task-
    # 批量执行主机命令线程池
    execHostCommandExecutor:
      synchronous-queue: true
      allow-core-timeout: true
      thread-name-prefix: exec-host-
    # 批量执行日志查看线程池
    execLogViewExecutor:
      synchronous-queue: true
      allow-core-timeout: true
      thread-name-prefix: exec-log-
    # 批量上传任务线程池
    uploadTaskExecutor:
      synchronous-queue: true
      allow-core-timeout: true
      thread-name-prefix: upload-task-
    # 批量上传主机线程池
    uploadHostExecutor:
      synchronous-queue: true
      allow-core-timeout: true
      thread-name-prefix: upload-host-
